### ISSUE TITLE
LDAPCursorError on Reader or EntryType object to pickle conversion when an attribute has 'no value'

### ISSUE THREAD

**Issue by stefb69** [cfelder/ldap3-orm#5]
Hello,

I've been trying to use ldap3-orm in a flask app to read and modify ldap entries from a live ldap server.

I initialise the object:

```python
UserDef = ObjectDef(["posixAccount","PureFTPdUser"], conn)
search_base = base_dn
r = Reader(conn, UserDef, search_base )
users = r.search() # Users are correctly returned (can see in the debugger)
```

But when an attribute has no value, i get 
```
File "C:\Python37\lib\site-packages\ldap3\abstract\entry.py", line 196, in __getattr__
    raise LDAPCursorError(error_message)
ldap3.core.exceptions.LDAPCursorError: attribute '__getstate__' not found
```
when i try to convert the data to send the data back using
```python
return pickle.dumps(users) if users is not None else ('Not found', 404)
```

Is this an issue with upstream ldap3 like #2 or am I doing something wrong ?

Thanks in advance for your help.

**Comment by cfelder** [comment]
Thanks for reaching out @stefb69. I can confirm that pickling objects derived from `ldap3.abstract.entry.EntryBase` is an upstream issue. Unfortunately ``__getattr__`` doesn't raise ``AttributeError`` which is against the specification.

> This method should either return the (computed) attribute value or raise an AttributeError exception.

https://docs.python.org/3/reference/datamodel.html?highlight=__getattr__#object.__getattr__

But this is not the only issue which prevents from pickling. I need to dig a bit more in it.

**Comment by cfelder** [comment]
Hello @stefb69.

I've created a upstream fix for your issue in cannatag/ldap3#748

**Comment by stefb69** [comment]
Hello,
Thanks for that, I will test this soon.

**Comment by stefb69** [comment]
I can confirm it is ok to pickle after applying your patch, thanks for that
