### ISSUE TITLE
Reader cursor operation failed without log

### ISSUE THREAD

**Issue by TcaManager** [cfelder/ldap3-orm#6]
Hi,
I created a reader, checked all info, also checked direct connection with Apache Directory studio.
The Reader says LAST OPERATION FAILED. How can I check what went wrong?
Thanks

I put *** to hide some words but the real code is correct.

```bash
<models.directory.LdapDirectory object at 0x7f2d4bfacc88>
CURSOR : Reader
CONN   : ldap://***.fr:12154 - cleartext - user: Directory manager - lazy - unbound - open - <local: 172.30.146.185:35824 - remote: 172.30.159.116:12154> - tls not started - listening - RestartableStrategy - internal decoder
DEFS   : top, person, organizationalPerson, inetOrgPerson, educationnationale
ATTRS  : [***]
BASE   : 'ou=***,ou=***,o=gouv,c=fr' [SUB]
FILTER : '(&(objectClass=top)(objectClass=person)(objectClass=organizationalPerson)(objectClass=inetOrgPerson)(objectClass=***))'
ENTRIES: 0 [executed at: 2019-10-24T14:46:44.703392]
LAST OPERATION FAILED [1 failure at operation 0]
```

**Comment by cfelder** [comment]
HI @TcaManager. I've just finished my vacation and checked the code of the `ldap3_orm.Reader <ldap3.abstract.cursor.Reader>` implementation which has an ``errors`` property returning a list of operations which have failed.

**Comment by cfelder** [comment]
Hi @TcaManager and a happy new year.

Does my previous answer satisfy your needs?

Best
Christian

**Comment by cfelder** [comment]
closed due to inactivity for more than 3 month.

Please reopen if you want to get back to this.
