### ISSUE TITLE
Unboud connection

### ISSUE THREAD

**Issue by TcaManager** [cfelder/ldap3-orm#7]
Hi,
Using code below, I get no entry in reader, what I don't get is that bind status change before and after calling the Reader search method. Is that normal? I'm not sure it is the cause of no entry result, but I suspect it is as anonymous search retrieve schema but cannot retrieve users. Thanks.

```python
from config import connection, user_entry_type, base_dn, user_search_filter

def search_users():
        reader = Reader(
            connection,
            user_entry_type._objDef,
            base_dn,
            user_search_filter
        )
        reader.search(attributes=ALL_ATTRIBUTES)
        return reader

print(connection)
r = search_users()
print(connection)
```

```bash
ldap://id-devops-7.in.ac-orleans-tours.fr:12154 - cleartext - user: Directory manager - lazy - deferred bind - deferred open - <no socket> - tls not started - not listening - RestartableStrategy - internal decoder
ldap://id-devops-7.in.ac-orleans-tours.fr:12154 - cleartext - user: Directory manager - lazy - unbound - open - <local: 172.30.146.185:47662 - remote: 172.30.159.116:12154> - tls not started - listening - RestartableStrategy - internal decoder
```

**Comment by cfelder** [comment]
Hello @TcaManager and a happy new year.

I need some more information about how you created the connection object or rather your configuration file if you're using ldap3-orm's auto created connection object `conn` from `ldap3_orm.connection` module.

From your output I expect you're using something similar like
```python
connconfig = dict(
    user = "cn=Directory Manager",
    password = keyring,
    lazy = True,
    client_strategy = "RESTARTABLE",
)
```

I had a look at the ldap3 code and from my point of view whether or not your connection is unbound depends on the connection result.

```python
self.bound = True if result['result'] == RESULT_SUCCESS else False
```

It would be good to know what's the result of
```python
print(connection.result)
```

If this doesn't pin point the problem getting some more log output (`ldap3.utils.log`) would be helpful.

Best
Christian

**Comment by cfelder** [comment]
closed due to inactivity for more than 3 month.

Please reopen if you want to get back to this.
